packages:
  - "packages/*"
  - "examples/*"

allowBuilds:
  esbuild: true
  lefthook: true

catalogs:
  dev:
    "@types/node": ^24.19.2
    typescript: "npm:@typescript/native-preview@7.0.0-dev.20260707.2"
    vitest: ^4.1.11
  prod: {}
  peer: {}

minimumReleaseAgeExclude:
  - "@types/node@24.19.2"
  - knip@6.41.0
