packages:
  - "packages/*"
  - "examples/*"

allowBuilds:
  core-js-pure: true
  dtrace-provider: true
  esbuild: true
  lefthook: true
  protobufjs: true
  re2: true

catalogs:
  dev:
    "@types/node": ^24.19.2
    typescript: ^7.0.2
    vitest: ^4.1.11
  prod: {}
  peer: {}

minimumReleaseAgeStrict: false
